---
- name: Set the hostname of the instance
  hostname:
    name: "{{ my_hostname | default(my_default_hostname) }}.{{ my_dns_zone | default(my_default_zone) }}"

- name: Gathering Facts...
  setup:

# - name: Set facts for the instance
#   set_fact:
#     ansible_fqdn: "{{ my_hostname | default(my_default_hostname) }}.{{ my_dns_zone | default(my_default_zone) }}"

- name: Deploy Ansible roles
  include_role:
    name: "{{ item }}"
  loop: "{{ my_ansible_roles | default(my_default_ansible_roles) }}"
  when: my_ansible_roles is defined or my_default_ansible_roles is defined
