---
# vars file for erwstx.install_awx
git_repo: "https://github.com/ansible/awx.git"
rpm_packages:
- git
- gettext
- ansible
- docker
- nodejs
- npm
- gcc-c++
- bzip2
- python-pip
pip_packages:
- docker
- docker-compose
