---
- name: Firewalld desactivated (if installed)
  service:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes

- name: SELinux desactivated
  selinux:
    state: disabled
  ignore_errors: yes

- name: Initiate reboot of the host
  reboot:
