---
- debug:
    msg: "AWX wont be deployed because the host is not running on CentOS"
  when: ansible_distribution != "CentOS"

- include_tasks: "{{ item }}"
  loop:
  - fw-selinux.yml
  - install.yml
  - service.yml
  - git.yml
  when:
  - ansible_distribution == "CentOS"
  - ansible_distribution_version == "7.6.1810"
